CREATE TABLE "TASK" COMMENT 'The tasks'(
	"TASK_ID" IDENTITY
		COMMENT 'The generated primary key'
		PRIMARY KEY,
	"NAME" VARCHAR(32)
		NOT NULL
		COMMENT 'The name of this task',
	"PSP_ASSIGNMENT_ID" INT8
		COMMENT 'The foreign key to the PSP assignment. NULL in case this is a sub task'
		REFERENCES "PSP_ASSIGNMENT",
	"PARENT_TASK_ID" INT8
		COMMENT 'The foreign key to the parent task. NULL in case its a root task'
		REFERENCES "TASK",
	CONSTRAINT "TASK_UNQ_NAME"
		UNIQUE("NAME", "PSP_ASSIGNMENT_ID", "PARENT_TASK_ID"),
	CONSTRAINT "TASK_CHK_PSP_ASSIGNMENT_ID"
		CHECK "PSP_ASSIGNMENT_ID" IS NOT NULL AND "PARENT_TASK_ID" IS NULL
			OR "PSP_ASSIGNMENT_ID" IS NULL AND "PARENT_TASK_ID" IS NOT NULL);
